---
apiVersion: v1
kind: Template
metadata:
  name: amq6-broker-custom
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: amq6-broker-custom
    name: amq6-broker-custom
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: amq6-broker-custom
    name: amq6-broker-custom
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: amq6-broker-custom:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/garethahealy/amq-jaas-cert.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-amq-63:1.4
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
